### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'json'

### ISSUE THREAD

**Issue by krubasaur** [krubasaur/api-experimentation#17]
```
HTTP Request failed
Traceback (most recent call last):
  File "tumblrapi/main.py", line 54, in <module>
    main()
  File "tumblrapi/main.py", line 47, in main
    print_tagged_posts('happy', 2)
  File "tumblrapi/main.py", line 12, in print_tagged_posts
    posts = request.get_tagged_posts(tag, limit)
  File "/Users/alana/Code/Projects/api-experimentation/tumblrapi/client.py", line 36, in get_tagged_posts
    response = self.get(url).json()
AttributeError: 'NoneType' object has no attribute 'json'
```

---

Came across this issue in testing. Only appeared once, I didn't alter any code after it appeared and it seems to have continued working except that one event. Not sure what the cause was but making a note of it here. Going to link it to the specific PR when I push today's commits.

**Comment by krubasaur** [comment]
haven't seen this issue since it originally occurred and the code is pretty different from what it was at the time. i'll reopen this if i see the issue again.
